<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="Mapster" Version="10.0.0" />
		<PackageReference Include="Mapster.DependencyInjection" Version="1.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ElectroPi.TaskManager.Domain\ElectroPi.TaskManager.Domain.csproj" />
	</ItemGroup>

</Project>