services:

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Logging__EnableSensitiveDataLogging=true
      - Logging__EnableDetailedErrors=true
    ports:
      - "5000:8080"
